name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: blog/pdf_doc_convert

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pdf2docx docx2pdf

    - name: Build EXE
      run: pyinstaller --onefile --noconsole convertor_gui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf_doc_converter
        path: blog/pdf_doc_convert/dist/*.exe
